#!/usr/bin/env perl

use warnings;
use strict;

use Getopt::Long;
use Pod::Usage;
use SOAP::Lite;

# global variables
my $warning  = 90;
my $critical = 30;
my $version  = 1;
my $help     = 0;
my $host;
my $revision;
my $debug;
my $tag;
my $community;
my $esx;

# variables needed for xserv.dell.com
my $soap_url = "http://xserv.dell.com/services/assetservice.asmx";
my $soap_uri = "http://support.dell.com/WebServices/";
my $guid     = "f1d49b55-a55c-44c1-baae-a244e1ae57d8";
my $appname  = "nagios warranty check";

#-------------------------------------------------------------------------------
# cli options
#-------------------------------------------------------------------------------
Getopt::Long::Configure( "no_ignore_case", "bundling" );
GetOptions(
    'H|host=s'      => \$host,
    't|tag=s'       => \$tag,
    'h|help|?'      => \$help,
    'v|verbose'     => \$debug,
    'V|version'     => \$revision,
    'w|warning=i'   => \$warning,
    'c|critical=i'  => \$critical,
    'C|community=s' => \$community,
    'E|esx=s'       => \$esx,
);

# get version info if requested and exit
if ($revision) {
    print "Version: $version\n";
    exit 0;
}

pod2usage(1) if $help;

pod2usage( -verbose => 1, -noperldoc => 1, ) unless $host;

#-------------------------------------------------------------------------------
#  process cli switches
#-------------------------------------------------------------------------------

if ( defined $debug ) {
    SOAP::Lite->import( trace => "debug" );
}

# if no tag is given from the cli and the check is run against localhost
# try getting it from dmidecode

if ( !defined $tag and $host eq "localhost" ) {
    dbg("Getting tag from dmidecode");
    _get_delltag_dmidecode();
    dbg("tag is $tag");
}

# try getting the $tag with snmp if we get a community cli switch
if ( defined $community ) {
    _get_tag_snmp( $host, $community );
}

# try getting the $tag using the VMware api
if ( defined $esx ) {
    _get_tag_esx();
}

# If we cannot get a $tag either from the cli options or dmidecode or
# snmp, then we cannot go on. End script then.
unless ( defined $tag ) {
    print
"We could not find an appropriate dell tag string. Without one we cannot use this plugin.\n";
    exit 3;
}

#-------------------------------------------------------------------------------
# main
#-------------------------------------------------------------------------------

# create soap agent
my $client = SOAP::Lite->new(
    proxy => $soap_url,
    uri   => $soap_uri,
);

# we need this, or it won't work
$client->on_action(
    sub {
        "http://support.dell.com/WebServices/GetAssetInformation";
    }
);

# poll the dell service with the requested info
my $call = $client->call(
    'GetAssetInformation',
    SOAP::Data->name('guid')->value($guid),
    SOAP::Data->name('applicationName')->value($appname),
    SOAP::Data->name('serviceTags')->value($tag),
);

die $call->faultstring if ( $call->fault );

# to see all the whole response uncomment these 2 lines
# use Data::Dumper;
# print Dumper $call->result;

# get some answers from the soap service:

# until when is our warranty valid?
my $end_date = $call->valueof('//Asset/Entitlements/EntitlementData/EndDate');

# is our warranty active now?
my $entitlement_type =
  $call->valueof('//Asset/Entitlements/EntitlementData/EntitlementType');

# how many days left do we have?
my $warranty_left =
  $call->valueof('//Asset/Entitlements/EntitlementData/DaysLeft');

if ($debug) {
    print "$tag still $warranty_left days left\n";
    print "entitlement type: \t $entitlement_type\n";
    print "end warranty date: \t $end_date\n";
}

# nagios logic/end of script
if ( $warranty_left > $warning ) {
    print
"OK: we have $warranty_left days. Warranty ends $end_date|days:$warranty_left\n";
    exit 0;
}
elsif ( $warranty_left <= $warning && $warranty_left >= $critical ) {
    print
"WARNING: we have $warranty_left days. Warranty ends $end_date|days:$warranty_left\n";
    exit 1;
}
elsif ( $warranty_left < $critical ) {
    print
"CRITICAL: we have $warranty_left days. Warranty ends $end_date|days:$warranty_left\n";
    exit 2;
}
else {
    print "UNKNOWN: run $0 with --verbose flag to see what has gone wrong\n";
    exit 3;
}

#-------------------------------------------------------------------------------
# subroutines
#-------------------------------------------------------------------------------

sub dbg {
    print STDERR "--", shift, "\n" if $debug;
}    # ----------  end of subroutine dbg  ----------

#===  FUNCTION  ================================================================
#         NAME:  _get_delltag_dmidecode
#      PURPOSE:  get the dell tag using dmidecode
#   PARAMETERS:
#      RETURNS:  dell tag string
#  DESCRIPTION:  when run on the localhost, we can get the dell tag
#                with dmidecode --type system
#       THROWS:  no exceptions
#     COMMENTS:  as this plugin will probably run as user nagios, we
#                need to use sudo. dmidecode can only run as root
#                To enable sudo dmidecode for the user nagios, edit the
#                sudoers file with visudo and set something like this:
#                nagios     ALL = NOPASSWD: /usr/sbin/dmidecode
#     SEE ALSO:  n/a
#===============================================================================
sub _get_delltag_dmidecode {
    my $dmidecode = "sudo dmidecode --type system";
    dbg("running and parsing $dmidecode");
    open my $outputdmidecode, '-|', $dmidecode or die "$!\n";
    while (<$outputdmidecode>) {
        chomp;    # dump hidden new lines please

        # we need to match Serial Number: *****, we save everything
        # after the : until a space in $1 which later becomes $tag
        # update: now we return the lower case tag after an update of
        # Dell's site
        if ( $_ =~ m/^.*Serial Number: (.*)\s*$/ ) {
            $tag = lc $1;
        }
    }

    close $outputdmidecode;

    dbg("this system\'s dell tag is $tag");

    return $tag;
}    # ----------  end of subroutine _get_delltag_dmidecode  ----------

#===  FUNCTION  ================================================================
#         NAME:  _get_tag_snmp
#      PURPOSE:  get the dell tag using snmp
#   PARAMETERS:  $host, $community
#      RETURNS:  dell tag string
#  DESCRIPTION:  get the dell tag using snmp
#       THROWS:  no exceptions
#     COMMENTS:  we use snmp version 1
#     SEE ALSO:  n/a
#===============================================================================
sub _get_tag_snmp {
    ( $host, $community ) = @_;

    dbg("polling $host with community $community using SNMP to get asset tag\n"
    );

    # create snmp object
    use Net::SNMP;

    my $oid_dell_tag = "1.3.6.1.4.1.674.10892.1.300.10.1.11.1";

    # start snmp session
    my ( $session, $error ) = Net::SNMP->session(
        -hostname  => $host,
        -community => $community,
        -version   => 1,

        #-debug     => 255,
    );

    # if the snmp session fails, exit check with error message
    if ( !defined $session ) {
        printf "ERROR: %s.\n", $error;
        exit 1;
    }

    # get the value in our wanted oid
    my $result = $session->get_request( -varbindlist => [$oid_dell_tag], );

    # if we cannot get a result, exit check with error message
    if ( !defined $result ) {
        printf "ERROR: %s.\n", $error;
        $session->close();
        exit 1;
    }

    # close snmp session, after this we parse the results we get
    $session->close();

    # uncomment this to see the snmp status
    $tag = $result->{$oid_dell_tag};
    dbg("got service tag [$tag] from snmp\n");

    return $tag;
}    # ----------  end of subroutine _get_tag_snmp  ----------

sub _get_tag_esx {

    # adapted from http://www.virtuallyghetto.com/
    # http://communities.vmware.com/docs/DOC-14652

    use VMware::VILib;
    use VMware::VIRuntime;
    Opts::set_option( 'server',   $host );
    Opts::set_option( 'username', "root" );
    Opts::set_option( 'password', "afkar#62" );
    Opts::parse();
    Opts::validate();
    Util::connect();

    my $host_view = Vim::find_entity_view( view_type => 'HostSystem' );
    my $additional_vendor_info = "";

    if ( $host_view->summary->hardware->otherIdentifyingInfo ) {
        my $add_info = $host_view->summary->hardware->otherIdentifyingInfo;
        foreach (@$add_info) {
            if ( $_->identifierType->key eq "ServiceTag" ) {
                $tag = $_->identifierValue;
                dbg("tag from ESX API: [$tag]\n");
            }
        }
    }
    else {
        dbg(
"There is no Service Tag information configured by your Vendor/OEM\n"
        );
    }
    return $tag;
}    # ----------  end of subroutine _get_tag_esx  ----------

#-------------------------------------------------------------------------------
#  Plain Old Documentation
#-------------------------------------------------------------------------------

=head1 NAME

dellkit_warranty

=head1 SYNOPSIS

# dellkit_warranty -H [hostname] -[tcwvVh]

=head1 DESCRIPTION

Nagios plugin to check the remaining days of warranty left for Dell
hardware.

The plugin requires the installation of the Soap::Lite module,
available from your Perl distributor repositories or CPAN.

=head1 ARGUMENTS

-H | --host     Hostname/ip address of server to monitor (required)

-t | --tag      Dell service tag number of server to monitor; if you do
not specify one on the command line, the script will try to get it from
dmidecode (only localhost), snmp (todo) or omreport (todo, only localhost)

-V | --version  prints the version of this program

-v | --verbose  prints extra debugging information

-w | --warning  days before nagios gives a warning; default is 90

-c | --critical days before nagios gives a critical alert; default is 30

-h | --help | -?  print this help text

=head1 AUTHOR

natxo asenjo in his spare time
